spring.application.name=student-library-system

server.port=7878

# MySQL DataSource properties
# database properties -> used to connect to mysql database
spring.datasource.url=jdbc:mysql://localhost:3306/student_library_april2026
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA and Hibernate properties (optional but commonly used)
#for automatically update database after every change
spring.jpa.hibernate.ddl-auto=update
#this will show the sql queries running internally in console
spring.jpa.show-sql=true
#it converts the java data types into database data type
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect